const iconVariants: { [key: string]: string[] } = {
  ArrowDown: ["filled", "outlined", "filled-1", "outlined-1"],
  Asiatech: [""],
  Aws: [""],
  Ayandeh: [""],
  Achareh: [""],

  Aio: [""],
  AlborzInsurance: [""],
  Alibaba: [""],
  Alopeik: [""],
  Anardooni: [""],
  Ansar: [""],
  Anten: [""],
  Aparat: [""],
  AparatKodak: [""],
  AparatSport: [""],
  Apple: [""],
  ArmanInsurance: [""],
  AsanPardakht: [""],
  Azki: [""],
  Banimode: [""],
  Basalam: [""],
  Bazar: [""],
  BimeBazar: [""],
  BimehCom: [""],
  Blu: [""],
  Alborz: [""],
  CaspianBank: [""],
  DanaInsurance: [""],
  DeyBank: [""],
  DeyInsurance: [""],
  DigiPay: [""],
  Digikala: [""],
  DigikalaJet: [""],
  Divar: [""],
  Django: [""],
  Eghtesad: [""],
  Erlang: [""],
  Eseminar: [""],
  Fidibo: [""],
  Filimo: [""],
  Filmnet: [""],
  Flightio: [""],
  Flutter: [""],
  Flytoday: [""],
  GardeshgariBank: [""],
  GhavaminBank: [""],
  Go: ["filled", "outlined", "filled-1"],
  HamrahAvval: [""],
  HekmatBank: [""],
  Hiweb: [""],
  Iapps: [""],
  Idpay: [""],
  IranVenezuelaBank: [""],
  IranZaminBank: [""],
  Irancell: [""],
  Iranicard: [""],
  Jabama: [""],
  Jobvision: [""],
  KarafarinBank: [""],
  KarafarinInsurance: [""],
  Karname: [""],
  KeshavarziBank: [""],
  Khanoumi: [""],
  KhavarMianehBank: [""],
  KosarBank: [""],
  KosarInsurance: [""],
  MaInsurance: [""],
  Maktabkhoone: [""],
  MarkaziBank: [""],
  MarkaziInsurance: [""],
  MaskanBank: [""],
  MehrEghtesad: [""],
  MehrIran: [""],
  MelallBank: [""],
  MellatBank: [""],
  MellatInsurance: [""],
  MelliBank: [""],
  Miare: [""],
  Mili: [""],
  MoalemInsurance: [""],
  Mobinnet: [""],
  Mrbillit: [""],
  Myket: [""],
  Namava: [""],
  Neshan: [""],
  NextPay: [""],
  Nobitex: [""],
  Nodejs: [""],
  NoorBank: [""],
  NovinInsurance: [""],
  Otaghak: [""],
  ParsianBank: [""],
  ParsianInsurance: [""],
  Parsonline: [""],
  PasargadBank: [""],
  PasargadInsurance: [""],
  PasargadPay: [""],
  Payfa: [""],
  Payping: [""],
  Pishgaman: [""],
  Ponisha: [""],
  Post: [""],
  Raastchin: [""],
  RaaziInsurance: [""],
  Reactjs: [""],
  RefahBank: [""],
  ResalatBank: [""],
  Rightel: [""],
  Sabanet: [""],
  Sadad: [""],
  SaderatBank: [""],
  SamanBank: [""],
  SamanInsurance: [""],
  SamanKish: [""],
  Samsung: [""],
  SanatMadanBank: [""],
  SarmayehBank: [""],
  Sep: [""],
  SepahBank: [""],
  ShahrBank: [""],
  Shatel: [""],
  Sheypoor: [""],
  Sibapp: [""],
  SinaBank: [""],
  SinaInsurance: [""],
  SnapPay: [""],
  Snapp: [""],
  SnappDoctor: [""],
  SnappFood: [""],
  SnappTrip: [""],
  TaavonInsurance: [""],
  Taghche: [""],
  Takhfifan: [""],
  Tamasha: [""],
  Tapsi: [""],
  Tecاnolife: [""],
  TejaratBank: [""],
  Telewebion: [""],
  Tesla: [""],
  Tipax: [""],
  Torob: [""],
  ToseeTaavonBank: [""],
  ToseeiInsurance: [""],
  Vandar: [""],
  Zarinpal: [""],
  Zhaket: [""],
  Zibal: [""],
  Zitel: [""],
  PostIran: ["outlined", "outlined-1"],
  AsiaInsurance: [""],
  Balad: [""],

  // :[""],
  // :[""],
  // :[""],
  // :[""],

  SingleVariants: ["Azki"],
  Sort: ["filled", "outlined", "filled-1", "outlined-1"],
  AirpodCase: ["filled", "outlined", "filled-1", "outlined-1"],
  Speaker: ["filled", "outlined", "filled-1", "outlined-1"],
  Watch: ["filled", "outlined", "filled-r", "outlined-r"],
  Document: [
    "filled",
    "filled-1",
    "filled-2",
    "filled-3",
    "outlined",
    "outlined-1",
    "outlined-2",
    "outlined-3",
  ],
  Brush: ["filled", "filled-1", "outlined", "outlined-1"],
  Crop: ["filled", "filled-1", "outlined", "outlined-1"],
  Chat: [
    "filled",
    "filled-1",
    "filled-2",
    "outlined",
    "outlined-1",
    "outlined-2",
  ],
  Filter: [
    "filled",
    "filled-1",
    "filled-2",
    "outlined",
    "outlined-1",
    "outlined-2",
  ],
  Menu: [
    "filled",
    "filled-1",
    "filled-2",
    "outlined",
    "outlined-1",
    "outlined-2",
  ],
  Grid: [
    "filled",
    "filled-1",
    "filled-2",
    "filled-3",
    "filled-4",
    "filled-5",
    "filled-6",
    "filled-7",
    "outlined",
    "outlined-1",
    "outlined-2",
    "outlined-3",
    "outlined-4",
    "outlined-5",
    "outlined-6",
    "outlined-7",
  ],
};

export default iconVariants;
